apiVersion: v1
kind: Service
metadata:
  name: ai-inference-api
  labels:
    app: ai-inference
spec:
  type: LoadBalancer
  selector:
    app: ai-inference
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
